/* Copyright (C) 2023 Harry Clark */

/* Dynamic DLL to DOL toolkit for Riivolution */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALUTY OF PARSING */
/* THE CONTENTS OF THE HEADER FILE OF THE EXTENSION FILE */

/* TAKING INTO ACCOUNT PLAUSIBLE ACTIONS THAT CORRESPOND TO */
/* THE PARSING OF BYTES THROUGH A RUDIMENTARY ORDER OF READING */

/* NESTED INCLUDES */

#include "util.h"

#ifdef DOL_HEADER

/* DETERMINE THE ORIGIN OF THE ALLOCATED OBJECT FILE MEMORY */
/* ON THE STACK BY DETEMINING THE SIZE OF THE PHYSICAL ADDRESS */
/* THE ADDRESS OF WHICH THE ALLOCATED MEMORY IS STORED IN THE BSS */

static inline DOL::INC_ALLOC* BSS_ALLOC_MEMORY(DOL* HEADER, ELF::TYPES* ELF)
{

#ifdef USE_UTIL

	/* THE FLAGS CORRESPOND TO THE DIFFERENT SECTIONS OF THE HEADER */
	/* PERTAINING TO FUNCTIONS SUCH AS THE ORIGIN, TEXT, AND ANY LIBRARIES */
	/* ASSOCIATED WITH THE ROM */

	if (DOL::FLAGS[8] & DOL_HAS_BSS)
	{
		HEADER->ORG += SWAP_BIG_ENDIAN(sizeof(HEADER->ADDR));
		HEADER->ORG_SIZE += SWAP_BIG_ENDIAN(sizeof(HEADER->SIZE));
		HEADER->ADDR += SWAP_BIG_ENDIAN(sizeof(ELF->PHYSICAL_ADDR));

		/* READ FROM THE PHYSICAL ADDRESS IN A BIG ENDIAN FASHION */
		/* AS AND WHEN THE ORIGIN IS PROPORTIONAL TO A PHYSICAL ADDRESS */
		/* OTHERWISE ALLOCATE OR THE MEMORY SIZE TO MAKE ACCMMODATIONS */

		if ((HEADER->ORG) += sizeof(ELF->PHYSICAL_ADDR))
		{
			HEADER->ORG_SIZE += SWAP_BIG_ENDIAN(sizeof(HEADER->SIZE));
		}

		else
		{
			HEADER->ORG += SWAP_BIG_ENDIAN(sizeof(ELF->PHYSICAL_ADDR));
			HEADER->ORG_SIZE += SWAP_BIG_ENDIAN(sizeof(ELF->MEM_SIZE));
			ELF->MEM_FLAGS = DOL_HAS_BSS;
		}
	}

#endif 

}

#endif

